GET http://localhost:3000/api/guitars

###

DELETE http://localhost:3000/api/guitars

###

POST http://localhost:3000/api/guitars
Content-Type: application/json

{
    "id": 5,
    "name": "gitarr",
    "price": 10000
}

###

PUT http://localhost:3000/api/guitars
